name: passcom-server

services:
  pg:
    image: postgres:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abacaxi01 
      POSTGRES_DB: passcom
    ports:
      - "5433:5433"

  passcom_app:
    image: passcom_app
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - pg
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:abacaxi01@pg:5432/passcom 

volumes:
  pgdata: