name: passcom-server

services:
  pg:
    image: postgres:11-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abacaxi01 
      - POSTGRES_DB=passcom
