"""att tabelas

Revision ID: 708d54fb838a
Revises: 
Create Date: 2024-10-28 15:34:59.880732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708d54fb838a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passagens', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('voos', sa.Column('capacidade_voo', sa.Integer(), nullable=False))
    op.add_column('voos', sa.Column('companhia_aerea', sa.String(), nullable=False))
    op.drop_column('voos', 'vagas')
    op.drop_column('voos', 'disponibilidade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voos', sa.Column('disponibilidade', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('voos', sa.Column('vagas', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('voos', 'companhia_aerea')
    op.drop_column('voos', 'capacidade_voo')
    op.drop_column('passagens', 'created_at')
    # ### end Alembic commands ###
